---
title: "Data Processes - Project Proposal"
author: "Angulo Luis Eduardo, Tahiri Oussama & Borrero Francisco"
date: "9/11/2019"
output:
  html_document: default
---

# Introduction


This project proposal is carry out as a part of the final project for the data processes class in the data science master of the Universidad Politécnica de Madrid.

# Domain of interest

## Why this domain?

## Examples of others data driven projects

* Projects:

  +

  +

  +

## Data driven questions

### Related to the field

### Can be answer with the data

## Findig data

### Link to URL where data is from

* Datasets:

1) Default of credit card clients Data Set
taken from: kaggle

  + URL where dataset is from [Dataset](https://www.kaggle.com/uciml/default-of-credit-card-clients-dataset)
  + Download the data into the project repo in a data/ folder
  + Description of how was the data collected or generated
  + How many observations (rows) and features (columns) are in your data?
  + What questions (from above) can be answered using the data in this dataset?

2) Credit Approval Data Set
taken from: UCI Machine Learning Repository

  + URL where dataset is from [Dataset](https://archive.ics.uci.edu/ml/datasets/Credit+Approval)
  + Download the data into the project repo in a data/ folder
  + Description of how was the data collected or generated
  + How many observations (rows) and features (columns) are in your data?
  + What questions (from above) can be answered using the data in this dataset?

3) Bank Marketing Data Set
  taken from: UCI Machine Learning Repository

  + URL where dataset is from [Dataset](http://archive.ics.uci.edu/ml/datasets/Bank+Marketing)
  + Download the data into the project repo in a data/ folder
  + Description of how was the data collected or generated
  + How many observations (rows) and features (columns) are in your data?
  + What questions (from above) can be answered using the data in this dataset?
